language: go
go:
  - "1.13"
sudo: false
notifications:
  email: false
os:
  - linux
  - osx
before_install:
  - npm install -g codeclimate-test-reporter
  - curl -sfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh| sh -s -- -b $(go env GOPATH)/bin v1.18.0
install:
  - go mod tidy
jobs:
  include:
    - stage: test
      script:
        - go build -race -v -gcflags "-N -l" .
        - ./go.test.sh
      after_success:
        - bash <(curl -s https://codecov.io/bash)
        - codeclimate-test-reporter < coverage.txt
